<?php
namespace petrabarus;
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface GeometryIf {
  /**
   * @param \petrabarus\Point $a
   * @param \petrabarus\Point $b
   * @return double
   */
  public function distance(\petrabarus\Point $a, \petrabarus\Point $b);
}

class GeometryClient implements \petrabarus\GeometryIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function distance(\petrabarus\Point $a, \petrabarus\Point $b)
  {
    $this->send_distance($a, $b);
    return $this->recv_distance();
  }

  public function send_distance(\petrabarus\Point $a, \petrabarus\Point $b)
  {
    $args = new \petrabarus\Geometry_distance_args();
    $args->a = $a;
    $args->b = $b;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'distance', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('distance', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_distance()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\petrabarus\Geometry_distance_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \petrabarus\Geometry_distance_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("distance failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class Geometry_distance_args extends TBase {
  static $_TSPEC;

  /**
   * @var \petrabarus\Point
   */
  public $a = null;
  /**
   * @var \petrabarus\Point
   */
  public $b = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'a',
          'type' => TType::STRUCT,
          'class' => '\petrabarus\Point',
          ),
        2 => array(
          'var' => 'b',
          'type' => TType::STRUCT,
          'class' => '\petrabarus\Point',
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Geometry_distance_args';
  }

  public function read($input)
  {
    return $this->_read('Geometry_distance_args', self::$_TSPEC, $input);
  }

  public function write($output) {
    $this->_validateForWrite();
    return $this->_write('Geometry_distance_args', self::$_TSPEC, $output);
  }

  private function _validateForWrite() {
    if ($this->a === null) {
      throw new TProtocolException('Required field Geometry_distance_args.a is unset!');
    }
    if ($this->b === null) {
      throw new TProtocolException('Required field Geometry_distance_args.b is unset!');
    }
  }

}

class Geometry_distance_result extends TBase {
  static $_TSPEC;

  /**
   * @var double
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::DOUBLE,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Geometry_distance_result';
  }

  public function read($input)
  {
    return $this->_read('Geometry_distance_result', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('Geometry_distance_result', self::$_TSPEC, $output);
  }

}


